name: sight_companion
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_tts: ^4.0.2
  tflite_v2: ^1.0.0
  image_picker: ^1.1.1
  palette_generator: ^0.3.3+3
  camera: ^0.10.5+9
  image: ^4.1.7
  speech_to_text: ^6.6.1
  flutter_scalable_ocr: ^2.0.0
  vibration: ^1.8.4
  flutter_barcode_scanner: ^2.0.0
  url_launcher: ^6.2.5
  simple_barcode_scanner: ^0.1.1
  google_mlkit_text_recognition: ^0.6.0
  tflite_flutter: ^0.10.4
  flutter_slider_drawer: ^2.1.3
  get: ^4.6.5
  avatar_glow: ^2.0.2
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  firebase_analytics: ^10.10.5
  firebase_core: ^2.31.0
  get_it: ^7.7.0
  delightful_toast: ^1.1.0
  google_fonts: ^6.2.1
  go_router: ^10.1.0
  badges: ^2.0.3
  ionicons: ^0.1.2
  flutter_svg: ^2.0.4
  step_progress_indicator: ^1.0.2
  cached_network_image: ^3.2.1
  transparent_image: ^2.0.0
  intl: ^0.18.0
  liquid_pull_to_refresh: ^3.0.1
  youtube_player_flutter: ^8.1.2
  flutter_launcher_icons: "^0.13.1"
  audioplayers: ^6.0.0
  provider: ^6.0.5
  equatable: ^2.0.5
  test: ^1.25.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/yolo.txt
    - assets/yolo.tflite
    - assets/signlangwage/
    - assets/signlangwage/numbers/
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/lottie/
    - assets/
    - assets/image/
    - assets/font/

  fonts:
    - family: EnliveIcons
      fonts:
        - asset: assets/fonts/EnliveIcons.ttf
